- name: mla_poc
  small:
    # used for correctness tests
    vocab_size: 50000
    d_model: 512
    d_head: 4
    d_kv_latent: 2
    num_heads: 4
    num_layers: 2
    max_seq_length: 2048
    max_batch_size: 1
  large:
    vocab_size: 50000
    d_model: 1024
    d_head: 64
    d_kv_latent: 128
    num_heads: 64
    num_layers: 12
    max_seq_length: 2048
    max_batch_size: 1
